<p class="centre">
    Please choose the method of transformation and pick a positive, integer number (other will default to zero):
</p>
<div class="centre">
    <select id="methodSelect">
        <option value="1" <?= $method==1 ? 'selected="selected"' : '' ?>>Normal</option>
        <option value="2" <?= $method==2 ? 'selected="selected"' : '' ?>>Traditional</option>
        <option value="3" <?= $method==3 ? 'selected="selected"' : '' ?>>Medieval</option>
    </select>
    <input type="text" id="numberInput" value="<?= $number ?>" />
    <button onclick="javascript:reload();">Do it!</button>
</div>
<div class="roman huge centre" style="overflow:auto;">
    <?= $result ?>
</div>

<article>
    <h3>About this page</h3>
    <p>
        This is a small code focused in the PHPUnit testing code and the PHP project itself. This project is not "RESTful" because it was not the aim of it.
    </p>
    <p>
        There is only one controller in this project and there are no models because there is no intention of persisting data.
    </p>
    <p>
        The JavaScript exists merely to reload the page with updated query strings and there is no sophisticated method of updating the data.
    </p>
</article>